apiVersion: v1
kind: Pod
metadata:
  name: centos-pod
  labels:
    app: centos
spec:
  containers:
  - name: centos-container
    image: centos:7
    command: ["/bin/sleep", "3600"]
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"

