apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /testinho
      name: primeiro-emptydir
    resources:
      limits:
        cpu: 1
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi
status: {}
