apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: teste-novo
    service: webserver
  name: teste-novo
spec:
  containers:
  - image: nginx
    name: teste-novo
    ports:
    - containerPort: 80
    resources: {}
  - image: busybox
    name: busybox
    args:
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
